### ISSUE TITLE
Inquiry on Potential Gas or Security Issues for Large Supply Collections

### ISSUE THREAD

**Issue by myst4** [Vectorized/dn404#100]
Hello,
I'm considering creating a collection with a supply of 100,000 items and wanted to consult on whether this could potentially lead to any issues regarding gas fees or security within the collection. Specifically, I'm concerned about whether such a large supply might cause transactions to become excessively expensive or if there are any security vulnerabilities that could arise from managing a collection of this size. Additionally, is there a risk of the collection's transactions getting stuck or failing due to the high number of items?

Could you please advise on any best practices or considerations I should be aware of to avoid potential issues with gas costs, security, or transaction reliability for a collection of this magnitude?

Thank you for your assistance.

**Comment by Vectorized** [comment]
100k should be fine, provided `_useExistsLookup()` is left as default, returning true.
