### ISSUE TITLE
Batch Minting like 721A's

### ISSUE THREAD

**Issue by cankaytaz** [Vectorized/dn404#106]
In our project, we need the batch mint function so that we can perform a certain amount of multiple mints in advance for Airdrops. 
I prepared an ownerMint function before, but this causes NFTs to be minted with more than one transaction. I need a feature where I can mint multiple NFTs with a single transaction, like in ERC721A. I would be very happy if you could help me.
Since I am not very experienced in this field, I may make mistakes.

**Comment by Vectorized** [comment]
Just do:

```
_mint(owner(), _unit() * amount);
```

If you don't want to mint the actual NFTs to the owner (to save gas), 

```
_setSkipNFT(owner(), true);
_mint(owner(), _unit() * amount);
```

**Comment by cankaytaz** [comment]
Thank you. It works. Frankly, I never thought I would use the skipNFT function for this.

 _setSkipNFT(owner(), state);

I think it makes more sense to use state. In order to define the collection in OpenSea and edit the collection page, it is necessary to perform 1 mint operation as owner.

Have a nice day.

**Comment by cankaytaz** [comment]
It worked in my case. ty
