### ISSUE TITLE
Dosn't work with SafeTransferLib ?

### ISSUE THREAD

**Issue by kivanov82** [Vectorized/dn404#121]
One of my inner contracts is using `safeTransferFrom` from `https://github.com/vectorized/solady/blob/main/src/utils/SafeTransferLib.sol` , for `DN404.sol` part.
Based on my debugging that doesn't seem to trigger the associated 721 minting/transferring

Am I correct or missing here something?

**Comment by Vectorized** [comment]
You'll need to prank with the `to`, and then call `setSkipNFT(false)`.
