### ISSUE TITLE
pls guide 

### ISSUE THREAD

**Issue by ProximaCA** [Vectorized/dn404#44]
how to quick start? i need deploy sample404 and setdatauri with metadata?
i deploy
forge create --rpc-url https://eth-sepolia.g.alchemy.com/v2/I5R_DPzNUrL_15mmGyq-Er1M7v__ix7Y \
    --constructor-args "arodnaP" "ARODNAP" "100000000000000000000000" "0x4EE84e71803773EcBF0f312d9FE9752097B2190A" \
    --private-key  \
    --etherscan-api-key  \
    --verify \
    src/example/SimpleDN404.sol:SimpleDN404
https://sepolia.etherscan.io/address/0x56a3F935Eb1485A25082CadAd7db5Cfb7693DE5d
pls check

and where whitelist func? when i create pool i need add wl pool address?

**Comment by Vectorized** [comment]
Bro, you shoudn't leak your alchemy private API endpoint. 

All pools (smart contracts) are auto whitelisted.
