### ISSUE TITLE
✨When transferring ERC20 tokens, also consider transferring NFTs.

### ISSUE THREAD

**Issue by Alivers** [Vectorized/dn404#47]
1. Instead of burning and minting, transferring NFTs when transferring FT tokens
2. ERC721 transfer event should be emitted
3. Due to the issue of fragment quantity during the transfer, it may be necessary to additionally burn and mint an NFT
4. For burning, add the `free` NFTs tracking(tokenId and total Amount) with a tmp address (ie. `address(0)`)
5. For minting, get NFTs from the tmp address

Thanks for your reading! Not sure it makes sense.

**Comment by Vectorized** [comment]
This is intended. If someone transfers ERC20s, it means that they are not concerned with the rarities. 

Grails: ERC721 transfers.
Floors: ERC20 transfers.

**Comment by Vectorized** [comment]
We might make it an option in the future to allow recycling token Ids, but we have other priorities.
