### ISSUE TITLE
EIP-2612 support

### ISSUE THREAD

**Issue by zerotwodao** [Vectorized/dn404#70]
Since ERC20 of solady supports EIP-2612 I think it would make sense if DN404 also supports EIP-2612 as well.

Or, for the meantime I should be using the ERC20Permit extension from openzeppelin?

cc @Vectorized

**Comment by Vectorized** [comment]
Oh... u want 2612? We can add it. Nice suggestion.

**Comment by Vectorized** [comment]
Not sure how many dapps would actually benefit from 2612.

**Comment by zerotwodao** [comment]
@Vectorized Maybe we want this instead? https://github.com/Uniswap/permit2 😈

**Comment by AmadiMichael** [comment]
What if we go the route of auto approval of permit2 similar to polygon's [POL token](https://github.com/0xPolygon/pol-token/blob/main/src/PolygonEcosystemToken.sol)

**Comment by Vectorized** [comment]
2612 or permit2… which one is cheaper?

**Comment by AmadiMichael** [comment]
Depends. Permit2 can be used gaslessly so integrating it optionally here means that users do not have to approve permit2 for max uint256 beforehand. On the other hand, with 2612, not sure how many dapps use it. 

Though it's important to think of the malicious signing attack vector that it introduces

**Comment by Vectorized** [comment]
What is the canonical Permit2 address?
