### ISSUE TITLE
Get the NFT inventory of the wallet.

### ISSUE THREAD

**Issue by bkundev** [Vectorized/dn404#84]
How can I retrieve the list of NFTs from a wallet similar to the OpenZeppelin's `ERC721Enumerable `utility with functions like `tokenOfOwnerByIndex `and `tokenByIndex`? I've tried using `_getDN404Storage().owned[wallet].map[index]` but couldn't make it work. @Vectorized

**Comment by Vectorized** [comment]
Ah, we might add this some day as a convenience function:

https://github.com/Vectorized/dn404/blob/90fe9c957f8ee3ffa75bbef1bac7858fd3e44b9d/test/utils/mocks/MockDN404.sol#L90 <- for now, you can use this. Remove the checks, which are just for testing purposes.
