### ISSUE TITLE
Revert on dn404Fallback if fn selector is not recognized.

### ISSUE THREAD

**Issue by kneelsdev** [Vectorized/dn404#85]
This tripped us up as it causes incorrect method calls to succeed silently rather than revert:

Incorrect call: https://sepolia.etherscan.io/tx/0x1383a9632316ab2b8f8d505422aeead15ba15d041534de53765b2e4739d8cf29
Correct call: https://sepolia.etherscan.io/tx/0x6933ad54b8c372f6b003a09cf02be6c3cee40b7b7fe3bfca2d6fa6723bbddc06

My proposed solution:
https://github.com/guminc/contracts/pull/76/commits/72dd9c38df50e45c40ff429416061b3d04d09451

**Comment by Vectorized** [comment]
Looks good. We might add it.
